checkstyle/patch-filters

.gitignore, config/import-control.xml, pom.xml, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java, src/main/java/com/github/checkstyle/generatepatchfile/Utils.java, src/main/java/com/github/checkstyle/generatepatchfile/package-info.java, src/main/resources/baseConfig.xml, src/main/resources/patchConfig.xml, src/test/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileTest.java, src/test/resources/com/github/checkstyle/patchfilter/InputCaseOne/InputCaseOneOrigin.java, src/test/resources/com/github/checkstyle/patchfilter/InputCaseOne/InputCaseOneUpdate.java, src/test/resources/com/github/checkstyle/patchfilter/InputCaseThree/InputCaseThreeOrigin.java, src/test/resources/com/github/checkstyle/patchfilter/InputCaseThree/InputCaseThreeUpdate.java, src/test/resources/com/github/checkstyle/patchfilter/InputCaseTwo/InputCaseTwoOrigin.java, src/test/resources/com/github/checkstyle/patchfilter/InputCaseTwo/InputCaseTwoUpdate.java, src/test/resources/com/github/checkstyle/patchfilter/JavadocMethod/JavadocMethodOneUpdate.java, src/test/resources/com/github/checkstyle/patchfilter/JavadocMethod/JavadocMethodOrigin.java, src/test/resources/com/github/checkstyle/patchfilter/JavadocMethod/JavadocMethodTwoUpdate.java, src/test/resources/com/github/checkstyle/patchfilter/MagicNumber/MagicNumberOrigin.java, src/test/resources/com/github/checkstyle/patchfilter/MagicNumber/MagicNumberUpdate.java, src/test/resources/com/github/checkstyle/patchfilter/MethodCount/MethodCountOrigin.java, src/test/resources/com/github/checkstyle/patchfilter/MethodCount/MethodCountUpdate.java, src/test/resources/com/github/checkstyle/patchfilter/MethodLine/MethodLineOrigin.java, src/test/resources/com/github/checkstyle/patchfilter/MethodLine/MethodLineUpdate.java, src/test/resources/com/github/checkstyle/patchfilter/MethodName/MethodNameOrigin.java, src/test/resources/com/github/checkstyle/patchfilter/MethodName/MethodNameUpdate.java, src/test/resources/com/github/checkstyle/patchfilter/ReturnCount/ReturnCountOrigin.java, src/test/resources/com/github/checkstyle/patchfilter/ReturnCount/ReturnCountUpdate.java
Issue #5: Script to iterate over git history and apply certain config  to code.
using generatePatch() can get patch file between any two commits in one repo. 
after getting the patch file. We can using it to test patch-filter, I make a draft PR(https://github.com/checkstyle/checkstyle/pull/8318) that put patch-filter into checkstyle to do checkstyle-tester.
three report examples on guava:
report file: https://huganghui.github.io/generatePatchReport/DiffReport/
baseBranch: master (the difference with patchBranch is not have new feature patch-filter's code), baseConfig with severity ignore. so no violations in report.
baseConfig:
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
"-//Puppy Crawl//DTD Check Configuration 1.3//EN"
"http://www.puppycrawl.com/dtds/configuration_1_3.dtd"> …
```
=> Issue #5: Script to iterate over git history and apply certain config  to code.

README.md, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileLauncher.java
Issue #18: update README to provide instruction on how to use report generator
=> Issue #18: update README to provide instruction on how to use report generator

config/suppressions.xml, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileWithGitCommandLauncher.java
Issue #19: update generator to generate patch file by 'git' commands
Maybe define an abstract class is a good idea?
=> Issue #19: update generator to generate patch file by 'git' commands

src/main/resources/patchConfig.xml
Issue #20: Change config to remove not relevant Check instances
=> Issue #20: Change config to remove not relevant Check instances

config/suppressions.xml, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileLauncher.java
minor: add suppression to supress UncommentedMain in GeneratePatchFileLauncher
=> minor: add suppression to supress UncommentedMain in GeneratePatchFileLauncher

src/main/java/com/github/checkstyle/patchfilter/SuppressionPatchFilterElement.java, src/test/java/com/github/checkstyle/patchfilter/SuppressionPatchFilterTest.java, src/test/resources/com/github/checkstyle/patchfilter/BoundaryTestPatchOne.txt
Issue #27: Fix boundary bug in PatchFilter
=> Issue #27: Fix boundary bug in PatchFilter

src/main/java/com/github/checkstyle/patchfilter/SuppressionPatchFilter.java, src/main/java/com/github/checkstyle/patchfilter/SuppressionPatchFilterElement.java, src/main/resources/patchConfig.xml
Issue #29: Fix Name bug in PatchFilter, details are in issue.
=> Issue #29: Fix Name bug in PatchFilter

src/main/resources/patchConfig.xml
Issue #20: remove Translation Check instances
=> Issue #20: remove Translation Check instances

src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java
Issue #33: make font on index.html good for usage from phone
=> Issue #33: make font on index.html good for usage from phone

src/main/java/com/github/checkstyle/patchfilter/SuppressionPatchFilterElement.java
Issue #38: resolve what not done in issue #27
=> Issue #38: resolve what not done in issue #27

src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileWithGitCommandLauncher.java
Issue #19 update generator to generate patch file by 'git show' commands
=> Issue #19 update generator to generate patch file by 'git show' commands

src/main/java/com/github/checkstyle/patchfilter/SuppressionPatchFilterElement.java, src/test/java/com/github/checkstyle/patchfilter/SuppressionPatchFilterTest.java
#54  minor: fix bugs about filename and boundary
ALL Test Pass
=> minor: fix bugs about filename and boundary

src/main/resources/patchConfig.xml
Issue #44: Cannot initialize module com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter
All Tests Pass except two tests in #41
=> Issue #44: Cannot initialize module com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter

README.md, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java
Issue #43: No such file or directory when trying to build a report
=> Issue # 43: No such file or directory when trying to build a report

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilter.java
Issue #55: extend AutomaticBean in SuppressionPatchFilter
=> Issue #55: extend AutomaticBean in SuppressionPatchFilter

src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java
Issue #19: update generator to generate patch file by 'git diff' commands
=> Issue #19: update generator to generate patch file by 'git diff' commands

README.md
Issue #59: Update README.md to avoid Hidden bug about commitID
=> Issue #59: Update README.md to avoid Hidden bug about commitID

src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java
Issue #37: update current generators to a context size equal to 0
=> Issue #37: update current generators to a context size equal to 0

src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java
Issue #64: Reset git repo to the initial state after report generation completed
=> Issue #64: Reset git repo to the initial state after report generation completed

src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/line/InputRegexpSingleline/Input.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/line/InputRegexpSingleline/config.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/line/InputRegexpSingleline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/line/InputRegexpSingleline/patch.diff
Input files based on the example from issue #74.
=> Issue #74: Input files for RegexpSingleline to test line strategy

src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java
This reverts commit 04f9d9e7446e46e4649b22e99fdbfc1670d2b415.
=> Revert "Issue #37: update current generators to a context size equal to 0"

src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/patchedline/InputRegexpSingleline/config.xml
=> minor: correct file property

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileLength/Test/Test2.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/patchedline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/zeroContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/LineLength/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/NewlineAtEndOfFile/Test/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/NewlineAtEndOfFile/Test/Test3.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/OrderedProperties/test.properties, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/RegexpMultiline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/RegexpOnFilename/Test/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/RegexpOnFilename/Test/Test3.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/RegexpSingleline/Input.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/UniqueProperties/test.properties
minor: add violation annotation to improve strategy's input files' readability
=> minor: add violation annotation to improve strategy's input files' readability

config/import-control.xml, config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/filters/LoadPatchFileUtils.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/TreeWalker/IllegalToken/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/TreeWalker/IllegalToken/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/TreeWalker/IllegalToken/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/TreeWalker/IllegalToken/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/TreeWalker/IllegalToken/newline/zeroContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/TreeWalker/IllegalToken/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/TreeWalker/IllegalToken/patchedline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/TreeWalker/IllegalToken/patchedline/zeroContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/TreeWalker/IllegalToken/zeroContext.patch
Issue #6: Create Treewalker filter SuppressionPatchXpathFilter that suppress all violations on non affected lines
=> Issue #6: Create Treewalker filter SuppressionPatchXpathFilter that suppress all violations on non affected lines

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileLength/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileLength/patchedline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/NewlineAtEndOfFile/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/NewlineAtEndOfFile/patchedline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/RegexpOnFilename/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/RegexpOnFilename/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/RegexpOnFilename/newline/zeroContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/RegexpOnFilename/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/RegexpOnFilename/patchedline/zeroContextConfig.xml
Issue #88: testByConfig should be able to process not only single file, but also directory
=> Issue #88: testByConfig should be able to process not only single file, but also directory

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilter.java
minor: update doc of neverSuppressedChecks
=> minor: update doc of neverSuppressedChecks

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/patchedline/defaultContextConfig.xml
Issue #155: SuppressionPatchXpathFilter: EmptyStatement's context strategy
=> Issue #155: SuppressionPatchXpathFilter: EmptyStatement's context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/patchedline/defaultContextConfig.xml
Issue #139: SuppressionPatchXpathFilter: EmptyBlock's context strategy
=> Issue #139: SuppressionPatchXpathFilter: EmptyBlock's context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/patchedline/defaultContextConfig.xml
Issue #178: SuppressionPatchXpathFilter: SimplifyBooleanReturn's context strategy
=> Issue #178: SuppressionPatchXpathFilter: SimplifyBooleanReturn's context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/patchedline/defaultContextConfig.xml
Issue #152: SuppressionPatchXpathFilter: DefaultComesLast's context strategy
```
default:  // violation context
break;
+            case 3:
+                break;
}
```
the default should be after all the cases in a switch statement, and `case 3` is not `default`'s child nodes.
=> Issue #152: SuppressionPatchXpathFilter: DefaultComesLast's context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/patchedline/defaultContextConfig.xml
Issue #195: SuppressionPatchXpathFilter: ThrowsCount's context strategy
=> Issue #195: SuppressionPatchXpathFilter: ThrowsCount's context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilter.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyCatchBlock/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MethodLength/case1/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MethodLength/case2/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ReturnCount/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/AnonInnerLength/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/ExecutableStatementCount/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/MethodCount/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/MethodLength/context/defaultContextConfig.xml
Issue #218: SuppressionPatchXpathFilter: new property 'supportContextStrategyChecks'
=> Issue #218: SuppressionPatchXpathFilter: new property 'supportContextStrategyChecks'

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/patchedline/defaultContextConfig.xml
Issue #193: SuppressionPatchXpathFilter: InterfaceIsType's context strategy
=> Issue #193: SuppressionPatchXpathFilter: InterfaceIsType's context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilter.java
minor: remove default values in SUPPORT_CONTEXT_STRATEGY_CHECKS
=> minor: remove default values in SUPPORT_CONTEXT_STRATEGY_CHECKS

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/context/Test1.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/newline/Test1.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/patchedline/Test1.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/patchedline/defaultContextConfig.xml
Issue #199: SuppressionPatchXpathFilter: OuterTypeFilename's context strategy
common pattern: https://github.com/checkstyle/patch-filters/issues/8#issuecomment-667061679
=> Issue #199: SuppressionPatchXpathFilter: OuterTypeFilename's context strategy

src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyBlock/patchedline/expected.txt
Issue #220: modify comment and add newline example about EmptyBlock
=> Issue #220: modify comment and add newline example about EmptyBlock

src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SimplifyBooleanReturn/patchedline/expected.txt
Issue #220: modify comment and add newline example about SimplifyBooleanReturn
=> Issue #220: modify comment and add newline example about SimplifyBooleanReturn

src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/patchedline/expected.txt
Issue #220: modify comment and add newline example about DefaultComesLast
=> Issue #220: modify comment and add newline example about DefaultComesLast

src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InterfaceIsType/patchedline/expected.txt
Issue #220: modify comment and add newline example about InterfaceIsType
=> Issue #220: modify comment and add newline example about InterfaceIsType

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalClass/patchedline/expected.txt
Issue #189: SuppressionPatchXpathFilter: FinalClass's context strategy
=> Issue #189: SuppressionPatchXpathFilter: FinalClass's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingCtor/patchedline/expected.txt
Issue #165: SuppressionPatchXpathFilter: MissingCtor's context strategy
=> Issue #165: SuppressionPatchXpathFilter: MissingCtor's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingSwitchDefault/patchedline/expected.txt
Issue #166: SuppressionPatchXpathFilter: MissingSwitchDefault's context strategy
=> Issue #166: SuppressionPatchXpathFilter: MissingSwitchDefault's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedIfDepth/patchedline/expected.txt
Issue #173: SuppressionPatchXpathFilter: NestedIfDepth's context strategy
=> Issue #173: SuppressionPatchXpathFilter: NestedIfDepth's context strategy

src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ThrowsCount/patchedline/expected.txt
Issue #220: modify comment and add newline example about ThrowsCount
=> Issue #220: modify comment and add newline example about ThrowsCount

src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/patchedline/expected.txt
Issue #220: modify comment and add newline example about ParameterNumber
=> Issue #220: modify comment and add newline example about ParameterNumber

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ImportOrder/patchedline/expected.txt
Issue #210: SuppressionPatchXpathFilter: ImportOrder's context strategy
=> Issue #210: SuppressionPatchXpathFilter: ImportOrder's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CustomImportOrder/patchedline/expected.txt
Issue #208: SuppressionPatchXpathFilter: CustomImportOrder's context strategy
=> Issue #208: SuppressionPatchXpathFilter: CustomImportOrder's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperFinalize/patchedline/expected.txt
Issue #234: SuppressionPatchXpathFilter: SuperFinalize's context strategy
=> Issue #234: SuppressionPatchXpathFilter: SuperFinalize's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RedundantImport/patchedline/expected.txt
Issue #212: SuppressionPatchXpathFilter: RedundantImport's context strategy
=> Issue #212: SuppressionPatchXpathFilter: RedundantImport's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedForDepth/patchedline/expected.txt
Issue #171: SuppressionPatchXpathFilter: NestedForDepth's context strategy
=> Issue #171: SuppressionPatchXpathFilter: NestedForDepth's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassDataAbstractionCoupling/patchedline/expected.txt
Issue #242: SuppressionPatchXpathFilter: ClassDataAbstractionCoupling's context strategy
=> Issue #242: SuppressionPatchXpathFilter: ClassDataAbstractionCoupling's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavaNCSS/patchedline/expected.txt
Issue #248: SuppressionPatchXpathFilter: JavaNCSS's context strategy
=> Issue #248: SuppressionPatchXpathFilter: JavaNCSS's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NPathComplexity/patchedline/expected.txt
Issue #250: SuppressionPatchXpathFilter: NPathComplexity's context strategy
=> Issue #250: SuppressionPatchXpathFilter: NPathComplexity's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OneTopLevelClass/patchedline/expected.txt
Issue #258: SuppressionPatchXpathFilter: OneTopLevelClass's context strategy
=> Issue #258: SuppressionPatchXpathFilter: OneTopLevelClass's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HideUtilityClassConstructor/patchedline/expected.txt
Issue #256: SuppressionPatchXpathFilter: HideUtilityClassConstructor's context strategy
=> Issue #256: SuppressionPatchXpathFilter: HideUtilityClassConstructor's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/BooleanExpressionComplexity/patchedline/expected.txt
Issue #240: SuppressionPatchXpathFilter: BooleanExpressionComplexity's context strategy
=> Issue #240: SuppressionPatchXpathFilter: BooleanExpressionComplexity's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DesignForExtension/patchedline/expected.txt
Issue #254: SuppressionPatchXpathFilter: DesignForExtension's context strategy
=> Issue #254: SuppressionPatchXpathFilter: DesignForExtension's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CyclomaticComplexity/patchedline/expected.txt
Issue #246: SuppressionPatchXpathFilter: CyclomaticComplexity's context strategy
=> Issue #246: SuppressionPatchXpathFilter: CyclomaticComplexity's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/PackageDeclaration/patchedline/expected.txt
Issue #238: SuppressionPatchXpathFilter: PackageDeclaration's context strategy
=> Issue #238: SuppressionPatchXpathFilter: PackageDeclaration's context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AtclauseOrder/patchedline/expected.txt
Issue #260: SuppressionPatchXpathFilter: AtclauseOrder's context strategy
common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-669225569
=> Issue #260: SuppressionPatchXpathFilter: AtclauseOrder's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NestedTryDepth/patchedline/expected.txt
Issue #174: SuppressionPatchXpathFilter: NestedTryDepth's context strategy
=> Issue #174: SuppressionPatchXpathFilter: NestedTryDepth's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ClassFanOutComplexity/patchedline/expected.txt
Issue #244: SuppressionPatchXpathFilter: ClassFanOutComplexity's context strategy
=> Issue #244: SuppressionPatchXpathFilter: ClassFanOutComplexity's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Regexp/patchedline/defaultContextConfig.xml
Issue #206: SuppressionPatchXpathFilter: Regexp's context strategy
this problem is that the all violations' information line is `0`, similar to Checks: `UniqueProperties`, `RegexpMultiline`.
common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-667101466
=> Issue #206: SuppressionPatchXpathFilter: Regexp's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DeclarationOrder/patchedline/expected.txt
Issue #252: SuppressionPatchXpathFilter: DeclarationOrder's context strategy
=> Issue #252: SuppressionPatchXpathFilter: DeclarationOrder's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OverloadMethodsDeclarationOrder/patchedline/expected.txt
Issue #236: SuppressionPatchXpathFilter: OverloadMethodsDeclarationOrder's context strategy
=> Issue #236: SuppressionPatchXpathFilter: OverloadMethodsDeclarationOrder's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnusedImports/patchedline/expected.txt
Issue #214: SuppressionPatchXpathFilter: UnusedImports's context strategy
=> Issue #214: SuppressionPatchXpathFilter: UnusedImports's context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/neversuppressedchecks/UniqueProperties/shortName/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/neversuppressedchecks/UniqueProperties/shortName/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/neversuppressedchecks/UniqueProperties/shortName/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/neversuppressedchecks/UniqueProperties/shortName/test.properties, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/checkNamesForContextStrategyByTokenOrParentSet/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/checkNamesForContextStrategyByTokenOrParentSet/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/checkNamesForContextStrategyByTokenOrParentSet/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/checkNamesForContextStrategyByTokenOrParentSet/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/neverSuppressedChecks/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/neverSuppressedChecks/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/neverSuppressedChecks/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/neverSuppressedChecks/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/supportContextStrategyChecks/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/supportContextStrategyChecks/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/supportContextStrategyChecks/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ShortName/supportContextStrategyChecks/expected.txt
Issue #286: properties should accept short name of Checks
=> Issue #286: properties should accept short name of Checks

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Optional/false/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Optional/false/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Optional/false/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Optional/true/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/Optional/true/defaultContextConfig.xml
Issue #123: Property 'optional' should be applied to patch file loading
=> Issue #123: Property 'optional' should be applied to patch file loading

src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java
Issue #138: Fix line numbers collection for context strategy
=> Issue #138: Fix line numbers collection for context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/patchedline/expected.txt
Issue #118: SuppressionPatchFilter: Header's UT
common pattern: https://github.com/checkstyle/patch-filters/issues/7#issuecomment-671905967
=> Issue #118: SuppressionPatchFilter: Header's UT

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/patchedline/expected.txt
Issue #118: SuppressionPatchFilter: RegexpHeader's UT
https://github.com/checkstyle/patch-filters/issues/7#issuecomment-671905967
=> Issue #118: SuppressionPatchFilter: RegexpHeader's UT

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultComesLast/context/defaultContextConfig.xml
Issue #293: Fix DefaultComesLast's context strategy
=> Issue #293: Fix DefaultComesLast's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EqualsHashCode/patchedline/expected.txt
Issue #232: SuppressionPatchXpathFilter: EqualsHashCode's context strategy
=> Issue #232: SuppressionPatchXpathFilter: EqualsHashCode's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InvalidJavadocPosition/patchedline/expected.txt
Issue #265: SuppressionPatchXpathFilter: InvalidJavadocPosition's context strategy
=> Issue #265: SuppressionPatchXpathFilter: InvalidJavadocPosition's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/context/case2/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/context/case2/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/context/case2/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CommentsIndentation/patchedline/expected.txt
Issue #216: SuppressionPatchXpathFilter: CommentsIndentation's context strategy
=> Issue #216: SuppressionPatchXpathFilter: CommentsIndentation's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocMethod/patchedline/expected.txt
Issue #274: SuppressionPatchXpathFilter: MissingJavadocMethod's context strategy
=> Issue #274: SuppressionPatchXpathFilter: MissingJavadocMethod's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/context/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/newline/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/patchedline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocPackage/patchedline/package-info.java
Issue #276: SuppressionPatchXpathFilter: MissingJavadocPackage's context strategy
=> Issue #276: SuppressionPatchXpathFilter: MissingJavadocPackage's context strategy

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocVariable/patchedline/expected.txt
Issue #272: SuppressionPatchXpathFilter: JavadocVariable's context strategy
common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-666272689
=> Issue #272: SuppressionPatchXpathFilter: JavadocVariable's context strategy

src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyStatement/patchedline/expected.txt
Issue #231: Fix EmptyStatement's context strategy
=> Issue #231: Fix EmptyStatement's context strategy

src/main/java/com/puppycrawl/tools/checkstyle/filters/LoadPatchFileUtils.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/Strategy.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffOnOpenSourceTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/DefaultStrategy/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/DefaultStrategy/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/DefaultStrategy/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/DefaultStrategy/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultStrategy/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultStrategy/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultStrategy/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DefaultStrategy/expected.txt
Issue #300: Add default strategy for patch-filters
=> Issue #300: Add default strategy for patch-filters

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
Issue #291: Put some rows in SuppressionPatchFilterTest and SuppressionPatchXpathFilterTest to one row
=> Issue #291: Put some rows in SuppressionPatchFilterTest and SuppressionPatchXpathFilterTest to one row

README.md
Issue #299: Add SuppressionPatchXpathFilter introductions and descriptions in the README
=> Issue #299: Add SuppressionPatchXpathFilter introductions and descriptions in the README

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/DescendantToken/patchedline/expected.txt
Issue #201: SuppressionPatchXpathFilter: DescendantToken's context strategy
=> Issue #201: SuppressionPatchXpathFilter: DescendantToken's context strategy

README.md
Issue #299: Add SuppressionPatchFilter introductions and descriptions in the README
=> Issue #299: Add SuppressionPatchFilter introductions and descriptions in the README

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidDoubleBraceInitialization/patchedline/expected.txt
Issue #148: SuppressionPatchXpathFilter: AvoidDoubleBraceInitialization's context strategy
=> Issue #148: SuppressionPatchXpathFilter: AvoidDoubleBraceInitialization's context strategy

README.md
minor: rename PatchXpatch JavaPatch
=> minor: rename PatchXpatch JavaPatch

src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java
Issue #310: add more javadoc annotation in PatchXpathFilterElement's private methods
=> Issue #310: add more javadoc annotation in PatchXpathFilterElement's private methods

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/patchedline/expected.txt
Issue #135: SuppressionPatchXpathFilter: PackageAnnotation's context strategy
=> Issue #135: SuppressionPatchXpathFilter: PackageAnnotation's context strategy

src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/AvoidNestedBlocks/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/RightCurly/context/Test.java
Issue #302: add RightCurly and AvoidNestedBlocks's new suppressed violations
=> Issue #302: add RightCurly and AvoidNestedBlocks's new suppressed violations

src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/ArrayTrailingComma/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/ArrayTrailingComma/context/defaultContextConfig.xml
Issue #302: add ArrayTrailingComma to CHECK_TO_ANCESTOR_NODES_MAP
=> Issue #302: add ArrayTrailingComma to CHECK_TO_ANCESTOR_NODES_MAP

src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/DeclarationOrder/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/DeclarationOrder/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/DefaultComesLast/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/DefaultComesLast/context/defaultContextConfig.xml
Issue #302: add DeclarationOrder and DefaultComesLast to CHECK_TO_ANCESTOR_NODES_MAP
=> Issue #302: add DeclarationOrder and DefaultComesLast to CHECK_TO_ANCESTOR_NODES_MAP

src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/EqualsHashCode/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/EqualsHashCode/context/defaultContextConfig.xml
Issue #302: add EqualsHashCode to CHECK_TO_ANCESTOR_NODES_MAP
=> Issue #302: add EqualsHashCode to CHECK_TO_ANCESTOR_NODES_MAP

src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/EmptyStatement/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/EmptyStatement/context/expected.txt
Issue #302: add EmptyStatement and EqualsHashCode to CHECK_TO_ANCESTOR_NODES_MAP
=> Issue #302: modify EmptyStatement to use checkNamesForContextStrategyByTokenOrParentSet property

src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/FallThrough/case1/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/FallThrough/case1/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/FallThrough/case2/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/FallThrough/case2/context/defaultContextConfig.xml
Issue #302: add FallThrough to CHECK_TO_ANCESTOR_NODES_MAP
=> Issue #302: add FallThrough to CHECK_TO_ANCESTOR_NODES_MAP

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/context/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/context/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/context/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/newline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/newline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/newline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/newline/expected.txt, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/patchedline/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/patchedline/defaultContext.patch, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/patchedline/defaultContextConfig.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/SummaryJavadocCheck/patchedline/expected.txt
Issue #280: SuppressionPatchXpathFilter: SummaryJavadocCheck's context strategy
common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-669225569
=> Issue #280: SuppressionPatchXpathFilter: SummaryJavadocCheck's context strategy

README.md
=> 306 maven release readme

src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/InnerTypeLast/context/Test.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/InnerTypeLast/context/defaultContextConfig.xml
Issue #302: add InnerTypeLast to CHECK_TO_ANCESTOR_NODES_MAP
=> Issue #302: add InnerTypeLast to CHECK_TO_ANCESTOR_NODES_MAP

README.md
Issue #308: List checks that will miss some violations when only use supportContextStrategyChecks property
please review and merge https://github.com/checkstyle/patch-filters/pull/303 first.
=> Issue #308: List checks that will miss some violations when only use supportContextStrategyChecks property

README.md
Issue #332: Update README.md to add checkNamesForContextStrategyByTokenOrAncestorSet property
=> Issue #332: Update README.md to add checkNamesForContextStrategyByTokenOrAncestorSet property

.github/workflows/maven.yml, config/suppressions.xml, pom.xml, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileLauncher.java, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileWithGitCommandLauncher.java, src/main/java/com/github/checkstyle/generatepatchfile/Utils.java, src/main/java/com/github/checkstyle/generatepatchfile/package-info.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/LoadPatchFileUtils.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchFilterSet.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/Strategy.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/package-info.java, src/test/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/AbstractPatchFilterEvaluationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/AuditEventUtFormatter.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/BriefUtLogger.java, src/test/java/com/puppycrawl/tools/checkstyle/jgit/AbstractJgitPatchParserEvaluationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffOnOpenSourceTest.java, src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffWithContextSizeDefaultTest.java, src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffWithContextSizeZeroTest.java
Upgrade to Checkstyle 10 to sync with sevntu right now.
Identified at https://github.com/checkstyle/eclipse-cs/pull/377#issuecomment-1309716749
=> Upgrade to Checkstyle 10.0

pom.xml, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/AbstractPatchFilterEvaluationTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/annotation/MissingOverride/context/case2/expected.txt
=> Issue #343: upgrade to cs 10.3.3

pom.xml, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
Fixes https://github.com/checkstyle/patch-filters/issues/342
=> config: update checkstyle to 10.4

pom.xml
This completes all dependency upgrades except CS.
versions:display-dependency-updates:
````
[INFO] -----------------< com.puppycrawl.tools:patch-filters >-----------------
[INFO] Building patch-filters 1.2.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.13.0:display-dependency-updates (default-cli) @ patch-filters ---
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   com.puppycrawl.tools:checkstyle ......................... 10.0 -> 10.4
[INFO] 
[INFO] The following dependencies in Plugin Dependencies have newer versions:
[INFO]   com.puppycrawl.tools:checkstyle ......................... 10.0 -> 10.4
[INFO] 
[INFO] -------------------------------------------------------------- …
```
=> config: upgrade various dependencies

pom.xml
Seen at https://github.com/checkstyle/patch-filters/actions/runs/3456994146/jobs/5770125507#step:5:12 .
Accidental from one of my previous changes.
=> minor: remove accidental duplicate dependency

.github/workflows/maven.yml
Upgrade to the latest version.
=> infra: upgrade java workflow to version 3

src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterElement.java
#113
Details of issue at https://github.com/checkstyle/patch-filters/issues/113#issuecomment-1312808670 .
**This does NOT resolve the issue, we need a windows CI to confirm.**
=> Issue #113: resolves audit event matching on windows

.github/workflows/maven.yml, pom.xml, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileLauncher.java, src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileWithGitCommandLauncher.java, src/main/java/com/github/checkstyle/generatepatchfile/Utils.java, src/main/java/com/github/checkstyle/generatepatchfile/package-info.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/CrFilterInputStream.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/LoadPatchFileUtils.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchFilterSet.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/Strategy.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/package-info.java, src/test/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/AbstractPatchFilterEvaluationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/jgit/AbstractJgitPatchParserEvaluationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffOnOpenSourceTest.java, src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffWithContextSizeDefaultTest.java, src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffWithContextSizeZeroTest.java
=> Issue #369: Migrate repo to jdk17
