- src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java
minor: change mkdir to mkdirs to avoid IO exception not considered
> minor: change mkdir to mkdirs to avoid IO exception not considered

- config/suppressions.xml
minor: add GeneratePatchFile to suppress ClassDataAbstractionCoupling check, too many  Class Data Abstraction Coupling in GeneratePatchFile, now  is 10 (max allowed is 7)  it is hard to solve it quickly, so I think suppress it temporarily is good.
> minor: add GeneratePatchFile to suppress ClassDataAbstractionCoupling check

- README.md
- src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java
- src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileLauncher.java
Issue #50: Specify a list of commit hashes to generate report for
now I implement the function that you can use generateTwoCommitDiffPatch to generate any diff report with two commit SHA, for example the commit SHA 31999ae and the commit SHA before 31999ae——c34f584, so it will generate diff report
which represents the commit 31999ae. As for a list of commit hashes and generate reports for those commits, I will implement later.
> Issue #50: Specify a list of commit hashes to generate report for

- README.md
- src/main/resources/patchConfig.xml
Issue #34: use system variable to customize path patch
Need to modify `patch-filter-jar` in contribution repo: add to `<propertyExpansion>checkstyle.pathfilter.patch=${checkstyle.pathfilter.patch.from.env}</propertyExpansion>` to `contribution/checkstyle-tester/pom.xml`
```xml
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-checkstyle-plugin</artifactId>
<version>${checkstyle-plugin.version}</version>
<configuration>
<enableFilesSummary>false</enableFilesSummary>
<failsOnError>${checkstyle.failsOnError}</failsOnError>
<propertyExpansion>checkstyle.pathfilter.patch=${checkstyle.pathfilter.patch.from.env}</propertyExpansion>
</configuration>
</plugin>
```
> Issue #34: use system variable to customize path patch

- src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffWithContextSizeDefaultTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-default/HaveRemovedFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-default/HaveRenamedFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-default/MovedCodeInOneFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-default/MultiHunksOnOneFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-default/OnlyAdditionInOneFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-default/OnlyDeletionInOneFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-default/OnlyReplaceMentInOneFile.patch
Issue #76: Add unit tests to evaluate jgit patch parser (GitDiffCommandDefaultSize)
> Patch is generated via diff -Naru <file1/dir1> <file2/dir2> (using default context size) - Pull Request 1
> Issue #76: Add unit tests to evaluate jgit patch parser (GitDiffCommandDefaultSize)

- src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffWithContextSizeZeroTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-0/HaveRemovedFilePatch.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-0/HaveRenamedWithNoChangedFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-0/MovedCodeInOneFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-0/MultiHunksOnOneFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-0/OnlyAdditionInOneFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-0/OnlyDeletionInOneFile.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/jgit/gitdiff/context-size-0/OnlyReplaceMentInOneFile.patch
Issue #76: Add unit tests to evaluate jgit patch parser (GitDiffCommandZeroSize)
> Patch is generated via diff -Nar -U 0 <file1/dir1> <file2/dir2> (using context size = 0) - Pull Request 2
> Issue #76: Add unit tests to evaluate jgit patch parser (GitDiffCommandZeroSize)

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithMinorChanges/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithMinorChanges/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithMinorChanges/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithMinorChanges/newline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithMinorChanges/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithMinorChanges/patchedline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithMinorChanges/zeroContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithoutChanges/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithoutChanges/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithoutChanges/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithoutChanges/newline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithoutChanges/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithoutChanges/patchedline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/MoveCodeInSameFileWithoutChanges/zeroContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleChangedLine/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleChangedLine/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleChangedLine/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleChangedLine/newline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleChangedLine/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleChangedLine/patchedline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleChangedLine/zeroContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleNewLine/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleNewLine/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleNewLine/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleNewLine/newline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleNewLine/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleNewLine/patchedline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/strategy/FileTabCharacter/SingleNewLine/zeroContext.patch
Issue #92: Add Non-Treewalker filter tests to cover more cases(FileTabCharacter)
use case: 1, 2 have not finished until https://github.com/checkstyle/patch-filters/issues/88
use case 3, 4, 5, 6 have finished.
> Issue #92: Add Non-Treewalker filter tests to cover more cases(FileTabCharacter)

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/newline/messages_test.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/newline/messages_test_de.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/patchedline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/patchedline/messages_test.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseOne/patchedline/messages_test_de.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseThree/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseThree/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseThree/newline/messages_test.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseThree/newline/messages_test_de.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseThree/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseThree/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseThree/patchedline/messages_test.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseThree/patchedline/messages_test_de.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseTwo/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseTwo/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseTwo/newline/messages_test.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseTwo/newline/messages_test_de.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseTwo/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseTwo/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseTwo/patchedline/messages_test.properties
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Translation/caseTwo/patchedline/messages_test_de.properties
Issue #109: SuppressionPatchFilter: mention Translation as non supported Check in javadoc
As mentioned in https://github.com/checkstyle/patch-filters/issues/109#issuecomment-660956637, all violations' line information is `1`, how do we solve this check?
> Issue #109: SuppressionPatchFilter: mention Translation as non supported Check in javadoc

- src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ParameterNumber/patchedline/defaultContextConfig.xml
Issue #129: SuppressionPatchXpathFilter: ParameterNumberCheck's context strategy
this checks belongs to common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-665554887
And a special situation on `ParameterNumberCheck` is that it violation node is on IDENT not METHOD_DEF, for example, in UT example, the violation node is IDENT -> test [4:16] not METHOD_DEF -> METHOD_DEF [4:4], so we have to do special handing to get its parent node:
```
CLASS_DEF -> CLASS_DEF [3:0]
|--MODIFIERS -> MODIFIERS [3:0]
|   `--LITERAL_PUBLIC -> public [3:0]
|--LITERAL_CLASS -> class [3:7]
|--IDENT -> Test [3:13]
`--OBJBLOCK -> OBJBLOCK [3:18]
|--LCURLY -> { [3:18]
|--METHOD_DEF -> METHOD_DEF [4:4]
|   |--MODIFIERS -> MODIFIERS [4:4]
|   |   `--LITERAL_PUBLIC -> public [4:4]
|   |--TYPE …
```
> Issue #129: SuppressionPatchXpathFilter: ParameterNumberCheck's context strategy

- src/main/java/com/puppycrawl/tools/checkstyle/filters/PatchXpathFilterElement.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/context/Test1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/newline/Test1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/patchedline/Test1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/OuterTypeFilename/patchedline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/OuterTypeNumber/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/OuterTypeNumber/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/OuterTypeNumber/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/OuterTypeNumber/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/OuterTypeNumber/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/OuterTypeNumber/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/OuterTypeNumber/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/sizes/OuterTypeNumber/patchedline/expected.txt
Issue #222: Remove ALWAYS_MATCHING_CONTEXT_STRATEGY_CHECKS from PatchXpathFilterElement
> Issue #222: Remove ALWAYS_MATCHING_CONTEXT_STRATEGY_CHECKS from PatchXpathFilterElement

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case1/patchedline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FallThrough/case2/patchedline/defaultContextConfig.xml
Issue #157: SuppressionPatchXpathFilter: FallThrough's context strategy
this change is for a special case that if the deletion line is the last line, then although we consider deletion line information in #162, it still can not be matched, because the last line is out of range of current java version. for example:
```java
case 7:  // violation context line 20
i++; // line 21
break; // line 22
```
if we delete line 22, and we consider deletion line information 22, it still not ok, because now `getChildAstLineNo` just get 20-21, no 22
another problem:
```
case 1:
i++;
-                // falls through
case 2:  // violation context
```
deleted line ` // falls through` is not `case 2`'s child node.
> Issue #157: SuppressionPatchXpathFilter: FallThrough's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/EmptyLineSeparator/patchedline/expected.txt
Issue #204: SuppressionPatchXpathFilter: EmptyLineSeparator's context strategy
here is a problem described in https://github.com/checkstyle/patch-filters/issues/203
> Issue #204: SuppressionPatchXpathFilter: EmptyLineSeparator's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/NoCodeInFile/patchedline/expected.txt
Issue #197: SuppressionPatchXpathFilter: NoCodeInFile's context strategy
common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-667061679
```
/* only
comment
+add one line
present
*/
```
the violation line always is `1:`,  and this violation is the whole file only.
> Issue #197: SuppressionPatchXpathFilter: NoCodeInFile's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/SuperClone/patchedline/expected.txt
Issue #180: SuppressionPatchXpathFilter: SuperClone's context strategy
ignore reason is that:
`Test.java:10:19: Method 'clone' should call 'super.clone'.`, the violation node is IDENT -> clone [10:18] not METHOD_DEF -> METHOD_DEF [10:4], so context strategy that check whether child nodes changed will not work.
it it the same with https://github.com/checkstyle/patch-filters/pull/130#discussion_r460881245, 
>lets make method like isParentOfAbstractToken and if it return true - use both nodes in match.
but I am not clear how to know whether a node is a abstract node, please give me more information.
```
|--METHOD_DEF -> METHOD_DEF [10:4]
|   |--MODIFIERS -> MODIFIERS [10:4]
|   |   `--LITERAL_PUBLIC -> …
```
> Issue #180: SuppressionPatchXpathFilter: SuperClone's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/VariableDeclarationUsageDistance/patchedline/expected.txt
Issue #187: SuppressionPatchXpathFilter:VariableDeclarationUsageDistance's context strategy
this problem belongs to common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-665565892
```
a = a + b;
b = a + a;
System.out.println(a);
+        System.out.println(b);
count = b;  // violation context
}
```
`System.out.println(b);` are not child nodes of `count = b;`
> Issue #187: SuppressionPatchXpathFilter:VariableDeclarationUsageDistance's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/InnerTypeLast/patchedline/expected.txt
Issue #191: SuppressionPatchXpathFilter: InnerTypeLast's context strategy
```
class Test1 {
private String s; // OK
+    class InnerTest1 {}
public void test() {} // violation context
}
class Test2 {
private String s; // OK
-    public void InnerTest1() {}
+    class InnerTest1 {}
public void test() {} // violation context
```
add/delete/change some nodes, then it will cause a violation, but these add/delete/change nodes are not violation node's child node, so current strategy not work.
> Issue #191: SuppressionPatchXpathFilter: InnerTypeLast's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/MissingJavadocType/patchedline/expected.txt
Issue #278: SuppressionPatchXpathFilter: MissingJavadocType's context strategy
common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-666272689
> Issue #278: SuppressionPatchXpathFilter: MissingJavadocType's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocParagraph/patchedline/expected.txt
Issue #267: SuppressionPatchXpathFilter: JavadocParagraph's context strategy
common pattern: https://github.com/checkstyle/patch-filters/issues/8#issuecomment-669225569
> Issue #267: SuppressionPatchXpathFilter: JavadocParagraph's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CovariantEquals/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CovariantEquals/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CovariantEquals/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CovariantEquals/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CovariantEquals/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CovariantEquals/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CovariantEquals/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/CovariantEquals/patchedline/expected.txt
Issue #150: SuppressionPatchXpathFilter: CovariantEquals's context strategy
delete `equals(Object i)`, should have violation, but not now.
annotate `equals(Object i)`, should have violation, but not now.
> Issue #150: SuppressionPatchXpathFilter: CovariantEquals's context strategy

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterElement.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/WithSuppressionPatchFilter/contextSituation/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/WithSuppressionPatchFilter/contextSituation/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/WithSuppressionPatchFilter/contextSituation/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/WithSuppressionPatchFilter/contextSituation/expected.txt
Issue #284: Add a new matching method to avoid suppress violations that are passed by SuppressionPatchXapthFilter.
I try the solution mentioned in https://github.com/checkstyle/checkstyle/issues/8602#issuecomment-670525645, but one problem is that how do we deal with ClassNotFoundException that introduced by `Class.forName(sourceName);`, now I catch it and config suppression `<suppress checks="ReturnCount" files="SuppressionPatchFilterElement\.java"/>`.
```java
catch (ClassNotFoundException ex) {
System.out.println("an error occurred when load patch file" + ex);
return false;
}
```
> Issue #284: Add a new matching method to avoid suppress violations that are passed by SuppressionPatchXapthFilter

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/context/case2/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/context/case2/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/context/case2/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/context/case2/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/HiddenField/patchedline/expected.txt
Issue #164: SuppressionPatchXpathFilter: HiddenField's context strategy
one problem: 
```
public class Test {
+    private int test;
private void addTest(int test)  // violation context
{
```
this added line is not the child nodes of `test` violations' node.
> Issue #164: SuppressionPatchXpathFilter: HiddenField's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/UnnecessarySemicolonInEnumeration/patchedline/expected.txt
Issue #182: SuppressionPatchXpathFilter: UnnecessarySemicolonInEnumeration's context strategy
one problem:
```
A,
B,
;
-        six(){}
}
```
`six(){}` cause the violation, but it is not child node of ` ;`
> Issue #182: SuppressionPatchXpathFilter: UnnecessarySemicolonInEnumeration's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/RightCurly/patchedline/expected.txt
Issue #142: SuppressionPatchXpathFilter: RightCurly's context strategy
should have violation, but not now, because
```java
else
{
```
is not `}` 's child node.
---
```
}  // violation context
catch (Exception e)
{
-                break;
+                break;  //changed
}
finally
{
```
```
catch (Exception e)
{
``` 
is not `}`'s child node
> Issue #142: SuppressionPatchXpathFilter: RightCurly's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case1/patchedline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/FinalLocalVariable/case2/patchedline/defaultContextConfig.xml
Issue #163: SuppressionPatchXpathFilter: FinalLocalVariable's contextstrategy
similar https://github.com/checkstyle/patch-filters/pull/130#issue-455110382, the violation node is IDENT -> x [4:23] and IDENT -> y [4:30] not METHOD_DEF -> METHOD_DEF [4:4].
```
|--METHOD_DEF -> METHOD_DEF [4:4]
|   |--MODIFIERS -> MODIFIERS [4:4]
|   |   `--LITERAL_STATIC -> static [4:4]
|   |--TYPE -> TYPE [4:11]
|   |   `--LITERAL_INT -> int [4:11]
|   |--IDENT -> foo [4:15]
|   |--LPAREN -> ( [4:18]
|   |--PARAMETERS -> PARAMETERS [4:19]
|   |   |--PARAMETER_DEF -> PARAMETER_DEF [4:19]
|   |   |   |--MODIFIERS -> MODIFIERS [4:19]
|   |   |   |--TYPE -> TYPE [4:19]
|   |   |   |   `--LITERAL_INT -> int [4:19]
|   | …
```
> Issue #163: SuppressionPatchXpathFilter: FinalLocalVariable's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidNestedBlocks/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidNestedBlocks/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidNestedBlocks/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidNestedBlocks/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidNestedBlocks/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidNestedBlocks/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/AvoidNestedBlocks/newline/expected.txt
Issue #136: SuppressionPatchXpathFilter: AvoidNestedBlocks's context strategy
There is one problem that previous line removed/added/changed cause a violation, how do we solve this problem:
```
-        if (x == 1)
{  // violation context
x = 2;
}
```
removed line `if (x == 1)` will caused a violation, but ` if (x == 1)` is not child node of `{ `, so this violation will be suppressed, but should not.
second one is that:
```
-        if (x == 1)
+//        if (x == 1)
{  // violation context
x = 2;
}
```
```
|--SINGLE_LINE_COMMENT -> // [18:0]
|       |   `--COMMENT_CONTENT ->         if (x == 1)\n [18:2]
|       |--SLIST -> { [19:8]
|       |   |--EXPR -> EXPR [20:14]
|       |   |   `--ASSIGN -> = …
```
> Issue #136: SuppressionPatchXpathFilter: AvoidNestedBlocks's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocMethod/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocMethod/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocMethod/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocMethod/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocMethod/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocMethod/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocMethod/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocMethod/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocMethod/patchedline/expected.txt
Issue #262: SuppressionPatchXpathFilter: JavadocMethod's context strategy
common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-669225569
> Issue #262: SuppressionPatchXpathFilter: JavadocMethod's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/JavadocType/patchedline/expected.txt
Issue #270: SuppressionPatchXpathFilter: JavadocType's context strategy
common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-669225569
> Issue #270: SuppressionPatchXpathFilter: JavadocType's context strategy

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchxpathfilter/ArrayTrailingComma/patchedline/expected.txt
Issue #146: SuppressionPatchXpathFilter: ArrayTrailingComma's context strategy
```
2  // context violation
-                ,};
+                };
int[] a3 = new int[]{
1,
2  // context violation
-                ,
};
```
Problem: `};` and ` ,` are not child node of 2
> Issue #146: SuppressionPatchXpathFilter: ArrayTrailingComma's context strategy

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterElement.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/FileLength/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/FileLength/newline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/FileLength/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/FileLength/patchedline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/Header/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/NewlineAtEndOfFile/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/NewlineAtEndOfFile/newline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/NewlineAtEndOfFile/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/NewlineAtEndOfFile/patchedline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpHeader/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpOnFilename/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpOnFilename/newline/zeroContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpOnFilename/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpOnFilename/patchedline/zeroContextConfig.xml
Issue 295: Context strategy Checker patch filter shouldn't contain hardcoded checks
> Issue 295: Context strategy Checker patch filter shouldn't contain hardcoded checks

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingDeprecated/patchedline/expected.txt
Issue #131: SuppressionPatchXpathFilter: MissingDeprecated's context strategy 
As mentioned in https://github.com/checkstyle/patch-filters/issues/131#issuecomment-662466401, MissingDeprecated still does not support return log AST, so its context strategy should use `neverSuppressedChecks`
> Issue #131: SuppressionPatchXpathFilter: MissingDeprecated's context strategy

- pom.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/DefaultStrategy/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/EmptyLineSeparator/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/EmptyLineSeparator/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/EmptyLineSeparator/patchedline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/InnerTypeLast/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/InnerTypeLast/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/InnerTypeLast/patchedline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingJavadocType/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingJavadocType/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingJavadocType/patchedline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/VariableDeclarationUsageDistance/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/VariableDeclarationUsageDistance/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/VariableDeclarationUsageDistance/patchedline/expected.txt
Issue #317: Update checkstyle dependency from 8.33 to 8.35
As mentioned in https://github.com/checkstyle/patch-filters/issues/302#issuecomment-679627971, some checks do not update AbstractChecks to log DetailAST in checkstyle 8.33, so we need to update checkstyle dependency to 8.35.
> Issue #317: Update checkstyle dependency from 8.33 to 8.35

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/context/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/context/case2/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/context/case2/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/context/case2/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/context/case2/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/context/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/newline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/newline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/newline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/newline/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/patchedline/Test.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/patchedline/defaultContext.patch
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/patchedline/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/MissingOverride/patchedline/expected.txt
Issue #132: SuppressionPatchXpathFilter: MissingOverride's context strategy
common pattern https://github.com/checkstyle/patch-filters/issues/8#issuecomment-666272689
There are two problems when I solve MissingOverride's context strategy.
First Problem: There is only a deleted line, but this deleted line will cause a violation in MissingOverride: Test.java:6:5: Must include @java.lang.Override annotation when {@inheritdoc} Javadoc tag exists.
but now in current suppressionPatchXpathFilter version, we only consider the added/changed line, not deleted line. The reason that deleted line does not be considered is that deleted line does not belong to current java file that do checkstyle, so it is difficult to deal with it. now deleted line information has been considered in #162.
Second …
> Issue #132: SuppressionPatchXpathFilter: MissingOverride's context strategy

- src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/AvoidNestedBlocks/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/FinalLocalVariable/case1/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/FinalLocalVariable/case1/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/FinalLocalVariable/case2/context/defaultContextConfig.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/FinalLocalVariable/case2/context/expected.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/RightCurly/context/defaultContextConfig.xml
Issue #302: Implement checkNameForContextStrategyByTokenOrAncestorSet
this PR update `checkNameForContextStrategyByTokenOrParentSet` to `checkNameForContextStrategyByTokenOrAncestorSet`. This update does not affect original checks listed in https://github.com/checkstyle/patch-filters/issues/302#issuecomment-674096024 that using `ParentSet`, and will make 14 checks not need to use `neverSuppressedChecks ` now, which will solve or relieve the problem is mentioned in issue #125
> Issue #302: Implement checkNameForContextStrategyByTokenOrAncestorSet

- .github/workflows/maven.yml
https://github.com/checkstyle/patch-filters/actions/runs/3446645759/jobs/5751807354#step:4:9
Logs are spammed with constant download messages. This is to trim back on that so the logs are easier to read.
> infra: adds cache and removes transfers from github run

- pom.xml
- src/test/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/AbstractPatchFilterEvaluationTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffOnOpenSourceTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffWithContextSizeDefaultTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/jgit/GitDiffWithContextSizeZeroTest.java
Upgrading as I couldn't run tests in Eclipse on the project without downgrading JUnit runner. My tests are still failing, so I can't validate this change locally.
> config: upgrade tests to jupiter and drop junit 4

- src/test/java/com/puppycrawl/tools/checkstyle/jgit/AbstractJgitPatchParserEvaluationTest.java
Issue #113
** This is the SECOND to last PR hopefully. ** This fixes support in the 3 GitDiff tests.
`SuppressionJavaPatchFilterTest` is the only thing that remains with 2 failing tests.
> Issue #113: fixes for windows support in GitDiffs

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilterTest.java
Similar to https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L298-L300
When JGit fails, it doesn't throw an IOException (atleast not all the time). I was getting custom exceptions that extend IllegalArguments like when the `\r` was still in the file. When it happened it skipped displaying our chain of the exception. This will ensure we get our message in.
> allows to catch jgit exceptions in suppression filters

- .github/workflows/maven.yml
Adding more platforms in the CI.
The combination of https://github.com/checkstyle/patch-filters/pull/361 and this completes https://github.com/checkstyle/patch-filters/issues/113 .
> infra: enable more platform runs in CI

- config/checkstyle.properties
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filters/AbstractPatchFilterEvaluationTest.java
Roughly fixed issue #367.
Any side effects are out of consideration, but it works.
https://github.com/checkstyle/patch-filters/issues/367
> Added default locale to avoid tests failed on non-English machine.
